### PR TITLE
Authorize installation on PHP8

### PR DESCRIPTION
**Pull request by Th3Mouk**

### CODE REVIEW

**Comment by Th3Mouk** [comment]
Hi @webmozart ! I know you are probably busy but this one can be quickly merged IMO

**Comment by webmozart** [comment]
@Th3Mouk Thanks! Could you take care of the failing builds?

**Comment by Th3Mouk** [comment]
@webmozart I took the configuration of `assert` repo but a composer issue makes the build fail randomly I didn't found how to resolve it. If it's a problem with composer mirrors maybe the problem will be gone tomorrow.

**Comment by chris-doehring** [comment]
@Th3Mouk After a bit of searching I found a [solution for this in the Travis CI docs](https://docs.travis-ci.com/user/common-build-problems/#timeouts-installing-dependencies). I tested it on your forked changes and added `travis_retry` in front of `composer self update` and `composer update [...]` and it works.
It seems to be a known issue when installing dependencies.

But be aware that the unit tests under php 8 still fail, because the used phpunit version is not compatible with php 8.

**Comment by Th3Mouk** [comment]
@chris-doehring thanks for your help. I know about PHPUnit but it's a dead-end, because no version of PHPUnit will support both PHP 5.3 and PHP8. Either this lib drop support of PHP version under 7.4, or provide a non tested support of PHP8.
I have an idea but i don't know if it's possible. Instead of requiring phpunit in composer dependencies, we can install the right version during TravisCI build and have two tests folder.

@webmozart I also don't know if you must/want to support 3 major versions of PHP, if PHP8 involves some modifications.

**Comment by chris-doehring** [comment]
@Th3Mouk You are welcome! There could be a valid solution though:
* Replace the phpunit version constraint to `*`
* Find a solution to not use the setUp or tearDown methods within the tests, as there was a change in some phpunit version, that those methods must return `void`

Then, theoretically, it should work fine.

**Comment by Th3Mouk** [comment]
@webmozart can we have your opinion about supported versions of PHP in https://github.com/Th3Mouk/path-util/pull/1 ?

**Comment by embargo2710** [comment]
@webmozart Hello! Could you merge this PR for supporting PHP 8?

**Pull request closed without merging**
