### PR TITLE
Optimise canonicalize().

### PR DESCRIPTION
**Pull request by patternseek**
Hi, here's the PR. I've not done one before so let me know if I need to change anything.

### CODE REVIEW

**Comment by patternseek** [comment]
First commit failed for PHP < 5.4 due to use of new array literal style.

**Comment by patternseek** [comment]
Scrutinizer doesn't say why it failed as far as I can see. Looks like it might have been an internal error but I can't tell it to re-run the tests.

**Comment by patternseek** [comment]
fixes #5

**Comment by King2500** [comment]
Why not caching the canonicalized paths from INSIDE `canonicalize`?

**Comment by patternseek** [comment]
Because only the base paths repeat a lot as far as I could see, caching both lead to a huge amount of cached paths most of which looked like they were only checked once.

**Comment by patternseek** [comment]
After waiting 4.5 hours to add an empty path with "path map" in Puli, I thought I'd have another look at this. 

It seems my tests regarding base / full paths previously had been incorrect, the non-base paths /are/ also canonicalized repeatedly. So I've moved the cache back inside the canonicalize() function as suggested by @King2500. Runtime for my test is now 37 seconds. Down from an initial 4:50 with the current release.

**Comment by webmozart** [comment]
Hi, thanks for the commit! I've been thinking about this and I don't think this is the right solution. With the ever-growing cache, we might run out of memory on long-running scripts.

I think the right solution is to never call `canonicalize()` from within `Path` and change the Doc Blocks of all methods to expect canonical paths. Then users of the class need to explicitly canonicalize paths (e.g. before passing them to `isBasePath()`), but they can also optimize the canonicalization to be done only once per path.

**Comment by patternseek** [comment]
Fair enough. I'd suggest doing so as soon as possible though as the current arrangement is unusable with a larger repository. As I say I waited 4.5 hours trying to map an empty directory to a large repository before I just killed the command.

**Comment by webmozart** [comment]
Do you want to create a PR for that?

**Comment by patternseek** [comment]
I'm afraid it's beyond me really. I don't have the time to dig into how that could be achieved in Puli.

**Comment by webmozart** [comment]
I experimented around with removing the calls to `canonicalize()` from the `Path` class but figured that the class would become quite unusable then. I implemented your fixes with a bounded buffer in a7abae5bafa658d1446ba8ca6e922d0fc3e68022 and 33a04a8b632af1d2e34ed760b02d68f92a02da6a.

Thanks!

**Comment by patternseek** [comment]
Cool, looks good.

**Pull request closed without merging**
